In [1]:
import pandas as pd
import numpy as np
import os
from six.moves import urllib
import warnings
warnings.filterwarnings('ignore')

# data gathering

In [2]:
data_dir = './data/'
os.makedirs(data_dir, exist_ok=True)

data_urls =[ 
    "https://raw.githubusercontent.com/mohitmahi004/atliq_hotels_data/refs/heads/main/fact_bookings.csv",
    "https://raw.githubusercontent.com/mohitmahi004/atliq_hotels_data/refs/heads/main/dim_date.csv",
    "https://raw.githubusercontent.com/mohitmahi004/atliq_hotels_data/refs/heads/main/dim_hotels.csv",
    "https://raw.githubusercontent.com/mohitmahi004/atliq_hotels_data/refs/heads/main/dim_rooms.csv",
    "https://raw.githubusercontent.com/mohitmahi004/atliq_hotels_data/refs/heads/main/fact_aggregated_bookings.csv"
    ]
for url in data_urls:
    filename = os.path.basename(url)
    print(filename)

    filepath = os.path.join(data_dir, filename)
    print(filepath)
    
    print(f"Downloading!!! {filename}")
    urllib.request.urlretrieve(url,filepath)
    print(f"{filename} Downloading Completed!!!")

fact_bookings.csv
./data/fact_bookings.csv
Downloading!!! fact_bookings.csv
fact_bookings.csv Downloading Completed!!!
dim_date.csv
./data/dim_date.csv
Downloading!!! dim_date.csv
dim_date.csv Downloading Completed!!!
dim_hotels.csv
./data/dim_hotels.csv
Downloading!!! dim_hotels.csv
dim_hotels.csv Downloading Completed!!!
dim_rooms.csv
./data/dim_rooms.csv
Downloading!!! dim_rooms.csv
dim_rooms.csv Downloading Completed!!!
fact_aggregated_bookings.csv
./data/fact_aggregated_bookings.csv
Downloading!!! fact_aggregated_bookings.csv
fact_aggregated_bookings.csv Downloading Completed!!!

In [3]:
# reading the files in pandas
df_dim_date = pd.read_csv('./data/dim_date.csv')
df_dim_date

         date  mmm yy week no  day_type
0   01-May-22  May 22    W 19   weekend
1   02-May-22  May 22    W 19  weekeday
2   03-May-22  May 22    W 19  weekeday
3   04-May-22  May 22    W 19  weekeday
4   05-May-22  May 22    W 19  weekeday
..        ...     ...     ...       ...
87  27-Jul-22  Jul 22    W 31  weekeday
88  28-Jul-22  Jul 22    W 31  weekeday
89  29-Jul-22  Jul 22    W 31  weekeday
90  30-Jul-22  Jul 22    W 31   weekend
91  31-Jul-22  Jul 22    W 32   weekend

[92 rows x 4 columns]

In [4]:
df_dim_hotels = pd.read_csv('./data/dim_hotels.csv')
df_dim_hotels

    property_id  property_name  category       city
0         16558   Atliq Grands    Luxury      Delhi
1         16559  Atliq Exotica    Luxury     Mumbai
2         16560     Atliq City  Business      Delhi
3         16561      Atliq Blu    Luxury      Delhi
4         16562      Atliq Bay    Luxury      Delhi
5         16563   Atliq Palace  Business      Delhi
6         17558   Atliq Grands    Luxury     Mumbai
7         17559  Atliq Exotica    Luxury     Mumbai
8         17560     Atliq City  Business     Mumbai
9         17561      Atliq Blu    Luxury     Mumbai
10        17562      Atliq Bay    Luxury     Mumbai
11        17563   Atliq Palace  Business     Mumbai
12        18558   Atliq Grands    Luxury  Hyderabad
13        18559  Atliq Exotica    Luxury  Hyderabad
14        18560     Atliq City  Business  Hyderabad
15        18561      Atliq Blu    Luxury  Hyderabad
16        18562      Atliq Bay    Luxury  Hyderabad
17        18563   Atliq Palace  Business  Hyderabad
18        19558   Atliq Grands    Luxury  Bangalore
19        19559  Atliq Exotica    Luxury  Bangalore
20        19560     Atliq City  Business  Bangalore
21        19561      Atliq Blu    Luxury  Bangalore
22        19562      Atliq Bay    Luxury  Bangalore
23        19563   Atliq Palace  Business  Bangalore
24        17564  Atliq Seasons  Business     Mumbai

In [5]:
df_dim_rooms = pd.read_csv('./data/dim_rooms.csv')
df_dim_rooms

  room_id    room_class
0     RT1      Standard
1     RT2         Elite
2     RT3       Premium
3     RT4  Presidential

In [6]:
df_fact_aggregated_bookings = pd.read_csv('./data/fact_aggregated_bookings.csv')
df_fact_aggregated_bookings

      property_id check_in_date room_category  successful_bookings  capacity
0           16559     01-May-22           RT1                   25        30
1           19562     01-May-22           RT1                   28        30
2           19563     01-May-22           RT1                   23        30
3           17558     01-May-22           RT1                   13        19
4           16558     01-May-22           RT1                   18        19
...           ...           ...           ...                  ...       ...
9195        16563     31-Jul-22           RT4                   13        18
9196        16559     31-Jul-22           RT4                   13        18
9197        17558     31-Jul-22           RT4                    3         6
9198        19563     31-Jul-22           RT4                    3         6
9199        17561     31-Jul-22           RT4                    3         4

[9200 rows x 5 columns]

In [7]:
df_fact_bookings = pd.read_csv('./data/fact_bookings.csv')
df_fact_bookings

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
0,May012216558RT11,16558,2022-04-27,2022-05-01,2022-05-02,3,RT1,direct online,1.0,Checked Out,10010,10010
1,May012216558RT12,16558,2022-04-30,2022-05-01,2022-05-02,2,RT1,others,NaN,Cancelled,9100,3640
2,May012216558RT13,16558,2022-04-28,2022-05-01,2022-05-04,2,RT1,logtrip,5.0,Checked Out,9100,9100
3,May012216558RT14,16558,2022-04-28,2022-05-01,2022-05-02,2,RT1,others,NaN,Cancelled,9100,3640
4,May012216558RT15,16558,2022-04-27,2022-05-01,2022-05-02,4,RT1,direct online,5.0,Checked Out,10920,10920
...,...,...,...,...,...,...,...,...,...,...,...,...
134585,Jul312217564RT46,17564,2022-07-29,2022-07-31,2022-08-03,1,RT4,makeyourtrip,2.0,Checked Out,32300,32300
134586,Jul312217564RT47,17564,2022-07-30,2022-07-31,2022-08-01,4,RT4,logtrip,2.0,Checked Out,38760,38760
134587,Jul312217564RT48,17564,2022-07-30,2022-07-31,2022-08-02,1,RT4,tripster,NaN,Cancelled,32300,12920
134588,Jul312217564RT49,17564,2022-07-29,2022-07-31,2022-08-01,2,RT4,logtrip,2.0,Checked Out,32300,32300
134589,Jul312217564RT410,17564,2022-07-31,2022-07-31,2022-08-01,2,RT4,makeyourtrip,NaN,Cancelled,32300,12920

# Data Cleaning

In [8]:
df_dim_date

         date  mmm yy week no  day_type
0   01-May-22  May 22    W 19   weekend
1   02-May-22  May 22    W 19  weekeday
2   03-May-22  May 22    W 19  weekeday
3   04-May-22  May 22    W 19  weekeday
4   05-May-22  May 22    W 19  weekeday
..        ...     ...     ...       ...
87  27-Jul-22  Jul 22    W 31  weekeday
88  28-Jul-22  Jul 22    W 31  weekeday
89  29-Jul-22  Jul 22    W 31  weekeday
90  30-Jul-22  Jul 22    W 31   weekend
91  31-Jul-22  Jul 22    W 32   weekend

[92 rows x 4 columns]

In [9]:
df_dim_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      92 non-null     object
 1   mmm yy    92 non-null     object
 2   week no   92 non-null     object
 3   day_type  92 non-null     object
dtypes: object(4)
memory usage: 3.0+ KB

In [10]:
df_dim_date.isnull().sum()

date        0
mmm yy      0
week no     0
day_type    0
dtype: int64

In [11]:
df_dim_date['date']=pd.to_datetime(df_dim_date['date'])

In [12]:
df_dim_date

         date  mmm yy week no  day_type
0  2022-05-01  May 22    W 19   weekend
1  2022-05-02  May 22    W 19  weekeday
2  2022-05-03  May 22    W 19  weekeday
3  2022-05-04  May 22    W 19  weekeday
4  2022-05-05  May 22    W 19  weekeday
..        ...     ...     ...       ...
87 2022-07-27  Jul 22    W 31  weekeday
88 2022-07-28  Jul 22    W 31  weekeday
89 2022-07-29  Jul 22    W 31  weekeday
90 2022-07-30  Jul 22    W 31   weekend
91 2022-07-31  Jul 22    W 32   weekend

[92 rows x 4 columns]

In [13]:
df_dim_date.dtypes

date        datetime64[ns]
mmm yy              object
week no             object
day_type            object
dtype: object

In [14]:
df_dim_date['mmm yy']= pd.to_datetime(df_dim_date['mmm yy'], format="%b %y")

In [15]:
df_dim_date

         date     mmm yy week no  day_type
0  2022-05-01 2022-05-01    W 19   weekend
1  2022-05-02 2022-05-01    W 19  weekeday
2  2022-05-03 2022-05-01    W 19  weekeday
3  2022-05-04 2022-05-01    W 19  weekeday
4  2022-05-05 2022-05-01    W 19  weekeday
..        ...        ...     ...       ...
87 2022-07-27 2022-07-01    W 31  weekeday
88 2022-07-28 2022-07-01    W 31  weekeday
89 2022-07-29 2022-07-01    W 31  weekeday
90 2022-07-30 2022-07-01    W 31   weekend
91 2022-07-31 2022-07-01    W 32   weekend

[92 rows x 4 columns]

In [16]:
df_dim_date.dtypes

date        datetime64[ns]
mmm yy      datetime64[ns]
week no             object
day_type            object
dtype: object

In [17]:
df_dim_hotels

    property_id  property_name  category       city
0         16558   Atliq Grands    Luxury      Delhi
1         16559  Atliq Exotica    Luxury     Mumbai
2         16560     Atliq City  Business      Delhi
3         16561      Atliq Blu    Luxury      Delhi
4         16562      Atliq Bay    Luxury      Delhi
5         16563   Atliq Palace  Business      Delhi
6         17558   Atliq Grands    Luxury     Mumbai
7         17559  Atliq Exotica    Luxury     Mumbai
8         17560     Atliq City  Business     Mumbai
9         17561      Atliq Blu    Luxury     Mumbai
10        17562      Atliq Bay    Luxury     Mumbai
11        17563   Atliq Palace  Business     Mumbai
12        18558   Atliq Grands    Luxury  Hyderabad
13        18559  Atliq Exotica    Luxury  Hyderabad
14        18560     Atliq City  Business  Hyderabad
15        18561      Atliq Blu    Luxury  Hyderabad
16        18562      Atliq Bay    Luxury  Hyderabad
17        18563   Atliq Palace  Business  Hyderabad
18        19558   Atliq Grands    Luxury  Bangalore
19        19559  Atliq Exotica    Luxury  Bangalore
20        19560     Atliq City  Business  Bangalore
21        19561      Atliq Blu    Luxury  Bangalore
22        19562      Atliq Bay    Luxury  Bangalore
23        19563   Atliq Palace  Business  Bangalore
24        17564  Atliq Seasons  Business     Mumbai

In [18]:
df_dim_hotels.dtypes

property_id       int64
property_name    object
category         object
city             object
dtype: object

In [19]:
df_dim_hotels.isnull().sum()

property_id      0
property_name    0
category         0
city             0
dtype: int64

In [20]:
df_dim_rooms

  room_id    room_class
0     RT1      Standard
1     RT2         Elite
2     RT3       Premium
3     RT4  Presidential

In [21]:
df_dim_rooms.dtypes

room_id       object
room_class    object
dtype: object

In [22]:
df_dim_rooms.isnull().sum()

room_id       0
room_class    0
dtype: int64

In [23]:
df_fact_aggregated_bookings

      property_id check_in_date room_category  successful_bookings  capacity
0           16559     01-May-22           RT1                   25        30
1           19562     01-May-22           RT1                   28        30
2           19563     01-May-22           RT1                   23        30
3           17558     01-May-22           RT1                   13        19
4           16558     01-May-22           RT1                   18        19
...           ...           ...           ...                  ...       ...
9195        16563     31-Jul-22           RT4                   13        18
9196        16559     31-Jul-22           RT4                   13        18
9197        17558     31-Jul-22           RT4                    3         6
9198        19563     31-Jul-22           RT4                    3         6
9199        17561     31-Jul-22           RT4                    3         4

[9200 rows x 5 columns]

In [24]:
df_fact_aggregated_bookings.dtypes

property_id             int64
check_in_date          object
room_category          object
successful_bookings     int64
capacity                int64
dtype: object

In [25]:
df_fact_aggregated_bookings['check_in_date']=pd.to_datetime(df_fact_aggregated_bookings['check_in_date'])

In [26]:
df_fact_aggregated_bookings.dtypes

property_id                     int64
check_in_date          datetime64[ns]
room_category                  object
successful_bookings             int64
capacity                        int64
dtype: object

In [27]:
df_fact_aggregated_bookings

      property_id check_in_date room_category  successful_bookings  capacity
0           16559    2022-05-01           RT1                   25        30
1           19562    2022-05-01           RT1                   28        30
2           19563    2022-05-01           RT1                   23        30
3           17558    2022-05-01           RT1                   13        19
4           16558    2022-05-01           RT1                   18        19
...           ...           ...           ...                  ...       ...
9195        16563    2022-07-31           RT4                   13        18
9196        16559    2022-07-31           RT4                   13        18
9197        17558    2022-07-31           RT4                    3         6
9198        19563    2022-07-31           RT4                    3         6
9199        17561    2022-07-31           RT4                    3         4

[9200 rows x 5 columns]

In [28]:
df_fact_aggregated_bookings.isnull().sum()

property_id            0
check_in_date          0
room_category          0
successful_bookings    0
capacity               0
dtype: int64

In [29]:
df_fact_bookings

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
0,May012216558RT11,16558,2022-04-27,2022-05-01,2022-05-02,3,RT1,direct online,1.0,Checked Out,10010,10010
1,May012216558RT12,16558,2022-04-30,2022-05-01,2022-05-02,2,RT1,others,NaN,Cancelled,9100,3640
2,May012216558RT13,16558,2022-04-28,2022-05-01,2022-05-04,2,RT1,logtrip,5.0,Checked Out,9100,9100
3,May012216558RT14,16558,2022-04-28,2022-05-01,2022-05-02,2,RT1,others,NaN,Cancelled,9100,3640
4,May012216558RT15,16558,2022-04-27,2022-05-01,2022-05-02,4,RT1,direct online,5.0,Checked Out,10920,10920
...,...,...,...,...,...,...,...,...,...,...,...,...
134585,Jul312217564RT46,17564,2022-07-29,2022-07-31,2022-08-03,1,RT4,makeyourtrip,2.0,Checked Out,32300,32300
134586,Jul312217564RT47,17564,2022-07-30,2022-07-31,2022-08-01,4,RT4,logtrip,2.0,Checked Out,38760,38760
134587,Jul312217564RT48,17564,2022-07-30,2022-07-31,2022-08-02,1,RT4,tripster,NaN,Cancelled,32300,12920
134588,Jul312217564RT49,17564,2022-07-29,2022-07-31,2022-08-01,2,RT4,logtrip,2.0,Checked Out,32300,32300
134589,Jul312217564RT410,17564,2022-07-31,2022-07-31,2022-08-01,2,RT4,makeyourtrip,NaN,Cancelled,32300,12920

In [30]:
df_fact_bookings.isnull().sum()

booking_id               0
property_id              0
booking_date             0
check_in_date            0
checkout_date            0
no_guests                0
room_category            0
booking_platform         0
ratings_given        77907
booking_status           0
revenue_generated        0
revenue_realized         0
dtype: int64

In [31]:
df_fact_bookings.isnull().mean()*100

booking_id            0.000000
property_id           0.000000
booking_date          0.000000
check_in_date         0.000000
checkout_date         0.000000
no_guests             0.000000
room_category         0.000000
booking_platform      0.000000
ratings_given        57.884687
booking_status        0.000000
revenue_generated     0.000000
revenue_realized      0.000000
dtype: float64

In [32]:
df_fact_bookings['ratings_given']

0         1.0
1         NaN
2         5.0
3         NaN
4         5.0
         ...
134585    2.0
134586    2.0
134587    NaN
134588    2.0
134589    NaN
Name: ratings_given, Length: 134590, dtype: float64

In [33]:
df_fact_bookings['ratings_given'].mean()

np.float64(3.619003934160154)

In [34]:
df_fact_bookings['ratings_given'].median()

4.0

In [35]:
df_fact_bookings['ratings_given'].mode()

0    5.0
Name: ratings_given, dtype: float64

In [36]:
df_fact_bookings['ratings_given'] = df_fact_bookings['ratings_given'].fillna(df_fact_bookings['ratings_given'].median())

In [37]:
df_fact_bookings

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
0,May012216558RT11,16558,2022-04-27,2022-05-01,2022-05-02,3,RT1,direct online,1.0,Checked Out,10010,10010
1,May012216558RT12,16558,2022-04-30,2022-05-01,2022-05-02,2,RT1,others,4.0,Cancelled,9100,3640
2,May012216558RT13,16558,2022-04-28,2022-05-01,2022-05-04,2,RT1,logtrip,5.0,Checked Out,9100,9100
3,May012216558RT14,16558,2022-04-28,2022-05-01,2022-05-02,2,RT1,others,4.0,Cancelled,9100,3640
4,May012216558RT15,16558,2022-04-27,2022-05-01,2022-05-02,4,RT1,direct online,5.0,Checked Out,10920,10920
...,...,...,...,...,...,...,...,...,...,...,...,...
134585,Jul312217564RT46,17564,2022-07-29,2022-07-31,2022-08-03,1,RT4,makeyourtrip,2.0,Checked Out,32300,32300
134586,Jul312217564RT47,17564,2022-07-30,2022-07-31,2022-08-01,4,RT4,logtrip,2.0,Checked Out,38760,38760
134587,Jul312217564RT48,17564,2022-07-30,2022-07-31,2022-08-02,1,RT4,tripster,4.0,Cancelled,32300,12920
134588,Jul312217564RT49,17564,2022-07-29,2022-07-31,2022-08-01,2,RT4,logtrip,2.0,Checked Out,32300,32300
134589,Jul312217564RT410,17564,2022-07-31,2022-07-31,2022-08-01,2,RT4,makeyourtrip,4.0,Cancelled,32300,12920

In [38]:
df_fact_bookings.dtypes

booking_id            object
property_id            int64
booking_date          object
check_in_date         object
checkout_date         object
no_guests              int64
room_category         object
booking_platform      object
ratings_given        float64
booking_status        object
revenue_generated      int64
revenue_realized       int64
dtype: object

In [39]:
df_fact_bookings[["booking_date", "check_in_date", "checkout_date"]]=df_fact_bookings[["booking_date", "check_in_date", "checkout_date"]].apply(pd.to_datetime)

In [40]:
df_fact_bookings.dtypes

booking_id                   object
property_id                   int64
booking_date         datetime64[ns]
check_in_date        datetime64[ns]
checkout_date        datetime64[ns]
no_guests                     int64
room_category                object
booking_platform             object
ratings_given               float64
booking_status               object
revenue_generated             int64
revenue_realized              int64
dtype: object

In [41]:
df_fact_bookings['ratings_given'] = df_fact_bookings['ratings_given'].astype(int)

In [42]:
df_fact_bookings.dtypes

booking_id                   object
property_id                   int64
booking_date         datetime64[ns]
check_in_date        datetime64[ns]
checkout_date        datetime64[ns]
no_guests                     int64
room_category                object
booking_platform             object
ratings_given                 int64
booking_status               object
revenue_generated             int64
revenue_realized              int64
dtype: object

In [43]:
df_fact_bookings

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
0,May012216558RT11,16558,2022-04-27,2022-05-01,2022-05-02,3,RT1,direct online,1,Checked Out,10010,10010
1,May012216558RT12,16558,2022-04-30,2022-05-01,2022-05-02,2,RT1,others,4,Cancelled,9100,3640
2,May012216558RT13,16558,2022-04-28,2022-05-01,2022-05-04,2,RT1,logtrip,5,Checked Out,9100,9100
3,May012216558RT14,16558,2022-04-28,2022-05-01,2022-05-02,2,RT1,others,4,Cancelled,9100,3640
4,May012216558RT15,16558,2022-04-27,2022-05-01,2022-05-02,4,RT1,direct online,5,Checked Out,10920,10920
...,...,...,...,...,...,...,...,...,...,...,...,...
134585,Jul312217564RT46,17564,2022-07-29,2022-07-31,2022-08-03,1,RT4,makeyourtrip,2,Checked Out,32300,32300
134586,Jul312217564RT47,17564,2022-07-30,2022-07-31,2022-08-01,4,RT4,logtrip,2,Checked Out,38760,38760
134587,Jul312217564RT48,17564,2022-07-30,2022-07-31,2022-08-02,1,RT4,tripster,4,Cancelled,32300,12920
134588,Jul312217564RT49,17564,2022-07-29,2022-07-31,2022-08-01,2,RT4,logtrip,2,Checked Out,32300,32300
134589,Jul312217564RT410,17564,2022-07-31,2022-07-31,2022-08-01,2,RT4,makeyourtrip,4,Cancelled,32300,12920

In [44]:
df_fact_bookings[['revenue_generated', 'revenue_realized']] = df_fact_bookings[['revenue_generated', 'revenue_realized']].astype(float)

In [45]:
df_fact_bookings

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
0,May012216558RT11,16558,2022-04-27,2022-05-01,2022-05-02,3,RT1,direct online,1,Checked Out,10010.0,10010.0
1,May012216558RT12,16558,2022-04-30,2022-05-01,2022-05-02,2,RT1,others,4,Cancelled,9100.0,3640.0
2,May012216558RT13,16558,2022-04-28,2022-05-01,2022-05-04,2,RT1,logtrip,5,Checked Out,9100.0,9100.0
3,May012216558RT14,16558,2022-04-28,2022-05-01,2022-05-02,2,RT1,others,4,Cancelled,9100.0,3640.0
4,May012216558RT15,16558,2022-04-27,2022-05-01,2022-05-02,4,RT1,direct online,5,Checked Out,10920.0,10920.0
...,...,...,...,...,...,...,...,...,...,...,...,...
134585,Jul312217564RT46,17564,2022-07-29,2022-07-31,2022-08-03,1,RT4,makeyourtrip,2,Checked Out,32300.0,32300.0
134586,Jul312217564RT47,17564,2022-07-30,2022-07-31,2022-08-01,4,RT4,logtrip,2,Checked Out,38760.0,38760.0
134587,Jul312217564RT48,17564,2022-07-30,2022-07-31,2022-08-02,1,RT4,tripster,4,Cancelled,32300.0,12920.0
134588,Jul312217564RT49,17564,2022-07-29,2022-07-31,2022-08-01,2,RT4,logtrip,2,Checked Out,32300.0,32300.0
134589,Jul312217564RT410,17564,2022-07-31,2022-07-31,2022-08-01,2,RT4,makeyourtrip,4,Cancelled,32300.0,12920.0

In [46]:
df_fact_bookings.isnull().sum()

booking_id           0
property_id          0
booking_date         0
check_in_date        0
checkout_date        0
no_guests            0
room_category        0
booking_platform     0
ratings_given        0
booking_status       0
revenue_generated    0
revenue_realized     0
dtype: int64

In [47]:
from sqlalchemy import create_engine

In [ ]:
engine =  create_engine("mysql+pymysql://{user}:{pwd}@localhost:3306/{db}".format(user="root", pwd="Remember123",db="hotels_revenue_insights_db"))

In [ ]:
df_dim_date.to_sql(con=engine, name="dim_date", if_exists='replace', index=False)

92

In [ ]:
df_dim_hotels.to_sql(con=engine, name="dim_hotels", if_exists='replace', index=False)

25

In [ ]:
df_dim_rooms.to_sql(con=engine, name="dim_rooms", if_exists='replace', index=False)

4

In [ ]:
df_fact_aggregated_bookings.to_sql(con=engine, name="fact_aggregated_bookings", if_exists='replace', index=False)

9200

In [ ]:
df_fact_bookings.to_sql(con=engine, name="fact_bookings", if_exists='replace', index=False)

134590